/**
 * Reads all .en.ts and .fr.ts namespace files, extracts translation keys,
 * checks EN/FR parity, and generates src/lib/i18n/generated.ts with a
 * TranslationKey union type.
 *
 * Usage: npx tsx scripts/generate-i18n-types.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const NAMESPACES_DIR = path.resolve(__dirname, '../src/lib/i18n/namespaces');
const OUTPUT_FILE = path.resolve(__dirname, '../src/lib/i18n/generated.ts');

const KEY_REGEX = /['"]([a-zA-Z0-9_.]+)['"]\s*:/g;

function extractKeys(filePath: string): Set<string> {
	const content = fs.readFileSync(filePath, 'utf-8');
	const keys = new Set<string>();
	let match: RegExpExecArray | null;
	while ((match = KEY_REGEX.exec(content)) !== null) {
		keys.add(match[1]);
	}
	return keys;
}

function main(): void {
	const files = fs.readdirSync(NAMESPACES_DIR);
	const enFiles = files.filter((f) => f.endsWith('.en.ts')).sort();
	const frFiles = files.filter((f) => f.endsWith('.fr.ts')).sort();

	const allEnKeys = new Set<string>();
	const allFrKeys = new Set<string>();

	for (const f of enFiles) {
		const keys = extractKeys(path.join(NAMESPACES_DIR, f));
		keys.forEach((k) => allEnKeys.add(k));
	}

	for (const f of frFiles) {
		const keys = extractKeys(path.join(NAMESPACES_DIR, f));
		keys.forEach((k) => allFrKeys.add(k));
	}

	// Check parity
	const missingInFr = [...allEnKeys].filter((k) => !allFrKeys.has(k));
	const missingInEn = [...allFrKeys].filter((k) => !allEnKeys.has(k));

	let hasErrors = false;

	if (missingInFr.length > 0) {
		console.error('Keys present in EN but missing in FR:');
		missingInFr.forEach((k) => console.error(`  - ${k}`));
		hasErrors = true;
	}

	if (missingInEn.length > 0) {
		console.error('Keys present in FR but missing in EN:');
		missingInEn.forEach((k) => console.error(`  - ${k}`));
		hasErrors = true;
	}

	// Generate the union type
	const sortedKeys = [...allEnKeys].sort();
	const unionMembers = sortedKeys.map((k) => `\t| '${k}'`).join('\n');

	const output = `// AUTO-GENERATED by scripts/generate-i18n-types.ts — DO NOT EDIT
// Generated at: ${new Date().toISOString()}

export type TranslationKey =
${unionMembers};
`;

	fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
	console.log(`Generated ${OUTPUT_FILE} with ${sortedKeys.length} keys.`);

	if (hasErrors) {
		console.error('\nParity check FAILED. Fix missing translations above.');
		process.exit(1);
	}

	console.log('Parity check PASSED. EN and FR have identical key sets.');
}

main();
