import type { FrameworkOverride } from '../types';

export const ifrsOverrides: Map<string, FrameworkOverride> = new Map([
	['shareCapital', { code: '-', nameFr: 'Share Capital', nameEn: 'Share Capital' }],
	['legalReserve', { code: '-', nameFr: 'Other Reserves', nameEn: 'Other Reserves' }],
	['retainedEarnings', { code: '-', nameFr: 'Retained Earnings', nameEn: 'Retained Earnings' }],
	['currentYearResult', { code: '-', nameFr: 'Profit/(Loss) for the Year', nameEn: 'Current Year Result' }],
	['incomeSummary', { code: '-', nameFr: 'Income Summary', nameEn: 'Income Summary' }],
	['bankLoan', { code: '-', nameFr: 'Borrowings', nameEn: 'Bank Borrowings' }],
	['leaseLiability', { code: '-', nameFr: 'Lease Liability (IFRS 16)', nameEn: 'Lease Liability' }],
	['provisionForRisks', { code: '-', nameFr: 'Provisions (IAS 37)', nameEn: 'Provisions' }],
	['provisionForCharges', { code: '-', nameFr: 'Other Provisions (IAS 37)', nameEn: 'Other Provisions' }],
	['land', { code: '-', nameFr: 'Land', nameEn: 'Land' }],
	['buildings', { code: '-', nameFr: 'Buildings', nameEn: 'Buildings' }],
	['equipment', { code: '-', nameFr: 'Plant & Equipment', nameEn: 'Equipment' }],
	['furniture', { code: '-', nameFr: 'Office Equipment', nameEn: 'Office Equipment' }],
	['itEquipment', { code: '-', nameFr: 'IT Equipment', nameEn: 'IT Equipment' }],
	['vehicles', { code: '-', nameFr: 'Motor Vehicles', nameEn: 'Vehicles' }],
	['rouAsset', { code: '-', nameFr: 'Right-of-Use Asset (IFRS 16)', nameEn: 'Right-of-Use Asset' }],
	['accDeprBuildings', { code: '-', nameFr: 'Accum. Depr. - Buildings', nameEn: 'Accum. Depr. Buildings' }],
	['accDeprEquipment', { code: '-', nameFr: 'Accum. Depr. - Equipment', nameEn: 'Accum. Depr. Equipment' }],
	['accDeprFurniture', { code: '-', nameFr: 'Accum. Depr. - Office Equipment', nameEn: 'Accum. Depr. Furniture' }],
	['accDeprVehicles', { code: '-', nameFr: 'Accum. Depr. - Vehicles', nameEn: 'Accum. Depr. Vehicles' }],
	['merchandise', { code: '-', nameFr: 'Inventories', nameEn: 'Inventories' }],
	['rawMaterials', { code: '-', nameFr: 'Raw Materials', nameEn: 'Raw Materials' }],
	['finishedGoods', { code: '-', nameFr: 'Finished Goods', nameEn: 'Finished Goods' }],
	['accountsPayable', { code: '-', nameFr: 'Trade Payables', nameEn: 'Trade Payables' }],
	['accountsReceivable', { code: '-', nameFr: 'Trade Receivables', nameEn: 'Trade Receivables' }],
	['vatCollected', { code: '-', nameFr: 'VAT Payable', nameEn: 'VAT Payable' }],
	['vatDeductible', { code: '-', nameFr: 'VAT Receivable', nameEn: 'VAT Receivable' }],
	['employeesPayable', { code: '-', nameFr: 'Employee Benefits Payable', nameEn: 'Employee Benefits Payable' }],
	['socialChargesPayable', { code: '-', nameFr: 'Social Security Payable', nameEn: 'Social Security Payable' }],
	['bank', { code: '-', nameFr: 'Cash & Cash Equivalents', nameEn: 'Cash & Cash Equivalents' }],
	['pettyCash', { code: '-', nameFr: 'Petty Cash', nameEn: 'Petty Cash' }],
	['shortTermInvestments', { code: '-', nameFr: 'Financial Assets at FVTPL', nameEn: 'Short-Term Investments' }],
	['purchasesMerchandise', { code: '-', nameFr: 'Cost of Sales', nameEn: 'Cost of Sales' }],
	['salaryExpense', { code: '-', nameFr: 'Employee Benefit Expense', nameEn: 'Employee Benefit Expense' }],
	['socialChargesExpense', { code: '-', nameFr: 'Social Contribution Expense', nameEn: 'Social Contribution Expense' }],
	['depreciationExpense', { code: '-', nameFr: 'Depreciation & Amortisation', nameEn: 'Depreciation Expense' }],
	['interestExpense', { code: '-', nameFr: 'Finance Costs', nameEn: 'Finance Costs' }],
	['exchangeLoss', { code: '-', nameFr: 'Exchange Loss', nameEn: 'Exchange Loss' }],
	['incomeTaxExpense', { code: '-', nameFr: 'Income Tax Expense (IAS 12)', nameEn: 'Income Tax Expense' }],
	['salesMerchandise', { code: '-', nameFr: 'Revenue (IFRS 15)', nameEn: 'Revenue' }],
	['serviceRevenue', { code: '-', nameFr: 'Service Revenue (IFRS 15)', nameEn: 'Service Revenue' }],
	['interestIncome', { code: '-', nameFr: 'Finance Income', nameEn: 'Finance Income' }],
	['exchangeGain', { code: '-', nameFr: 'Exchange Gain', nameEn: 'Exchange Gain' }],
	['disposalGain', { code: '-', nameFr: 'Gain on Disposal', nameEn: 'Gain on Disposal' }],
	['rentExpense', { code: '-', nameFr: 'Short-Term Lease Expense', nameEn: 'Rent Expense' }],
	['insuranceExpense', { code: '-', nameFr: 'Insurance Expense', nameEn: 'Insurance Expense' }],
	['badDebtExpense', { code: '-', nameFr: 'Impairment Loss on Receivables', nameEn: 'Bad Debt Expense' }],
	/* Extended IFRS overrides */
	['statutoryReserve', { code: '-', nameFr: 'Other Reserves', nameEn: 'Other Reserves' }],
	['constructionInProgress', { code: '-', nameFr: 'Assets Under Construction', nameEn: 'Assets Under Construction' }],
	['workInProgress', { code: '-', nameFr: 'Work in Progress', nameEn: 'Work in Progress' }],
	['accruedExpenses', { code: '-', nameFr: 'Accrued Liabilities', nameEn: 'Accrued Liabilities' }],
	['accruedRevenue', { code: '-', nameFr: 'Contract Assets', nameEn: 'Contract Assets' }],
	['advancesToSuppliers', { code: '-', nameFr: 'Prepayments to Suppliers', nameEn: 'Prepayments to Suppliers' }],
	['incomeTaxPayable', { code: '-', nameFr: 'Current Tax Liability', nameEn: 'Current Tax Liability' }],
	['otherReceivables', { code: '-', nameFr: 'Other Receivables', nameEn: 'Other Receivables' }],
	['otherPayables', { code: '-', nameFr: 'Other Payables', nameEn: 'Other Payables' }],
	['dividendsPayable', { code: '-', nameFr: 'Dividends Payable', nameEn: 'Dividends Payable' }],
	['bankOverdraft', { code: '-', nameFr: 'Bank Overdraft', nameEn: 'Bank Overdraft' }],
	['purchasesRawMaterials', { code: '-', nameFr: 'Raw Materials Consumed', nameEn: 'Raw Materials Consumed' }],
	['costOfGoodsSold', { code: '-', nameFr: 'Cost of Sales - Inventory Variation', nameEn: 'Cost of Sales - Inventory Variation' }],
	['inventoryVariation', { code: '-', nameFr: 'Inventory Movement', nameEn: 'Inventory Movement' }],
	['freightIn', { code: '-', nameFr: 'Freight & Transport', nameEn: 'Freight & Transport' }],
	['externalServices', { code: '-', nameFr: 'Other External Charges', nameEn: 'Other External Charges' }],
	['maintenanceExpense', { code: '-', nameFr: 'Repairs & Maintenance', nameEn: 'Repairs & Maintenance' }],
	['telecomExpense', { code: '-', nameFr: 'Communication Costs', nameEn: 'Communication Costs' }],
	['taxesAndDuties', { code: '-', nameFr: 'Other Taxes', nameEn: 'Other Taxes' }],
	['provisionExpense', { code: '-', nameFr: 'Impairment & Provision Charges', nameEn: 'Impairment & Provision Charges' }],
	['exceptionalExpense', { code: '-', nameFr: 'Other Expenses', nameEn: 'Other Expenses' }],
	['otherOperatingRevenue', { code: '-', nameFr: 'Other Operating Income', nameEn: 'Other Operating Income' }],
	['operatingSubsidies', { code: '-', nameFr: 'Government Grants', nameEn: 'Government Grants' }],
	['inventoryProductionVar', { code: '-', nameFr: 'Change in Inventories of Finished Goods', nameEn: 'Change in Inventories of Finished Goods' }],
	['exceptionalIncome', { code: '-', nameFr: 'Other Income', nameEn: 'Other Income' }],
	['reversalOfProvisions', { code: '-', nameFr: 'Reversal of Impairment', nameEn: 'Reversal of Impairment' }],
	['salesFinishedGoods', { code: '-', nameFr: 'Revenue - Manufactured Products', nameEn: 'Revenue - Manufactured Products' }],
	['prepaidExpenses', { code: '-', nameFr: 'Prepayments', nameEn: 'Prepayments' }],
	['unearnedRevenue', { code: '-', nameFr: 'Contract Liabilities', nameEn: 'Contract Liabilities' }],
	['advancesFromCustomers', { code: '-', nameFr: 'Advances from Customers', nameEn: 'Advances from Customers' }],
	['otherLtDebt', { code: '-', nameFr: 'Other Long-Term Liabilities', nameEn: 'Other Long-Term Liabilities' }],
	['inventoryProvision', { code: '-', nameFr: 'Allowance for Inventory Obsolescence', nameEn: 'Allowance for Inventory Obsolescence' }],
	['vatPayable', { code: '-', nameFr: 'VAT Payable', nameEn: 'VAT Payable' }],
	['allowanceDoubtful', { code: '-', nameFr: 'Allowance for Doubtful Accounts (IFRS 9)', nameEn: 'Allowance for Doubtful Accounts' }],
	['revaluationSurplus', { code: '-', nameFr: 'Revaluation Surplus (IAS 16)', nameEn: 'Revaluation Surplus' }],
	['deferredTaxAsset', { code: '-', nameFr: 'Deferred Tax Asset (IAS 12)', nameEn: 'Deferred Tax Asset' }],
	['deferredTaxLiability', { code: '-', nameFr: 'Deferred Tax Liability (IAS 12)', nameEn: 'Deferred Tax Liability' }],
	['disposalLoss', { code: '-', nameFr: 'Loss on Disposal', nameEn: 'Loss on Disposal' }],
]);
