import type { FrameworkOverride } from '../types';

export const pcgOverrides: Map<string, FrameworkOverride> = new Map([
	['shareCapital', { code: '101', nameFr: 'Capital social', nameEn: 'Share Capital' }],
	['legalReserve', { code: '1061', nameFr: 'Réserve légale', nameEn: 'Legal Reserve' }],
	['retainedEarnings', { code: '12', nameFr: 'Report à nouveau', nameEn: 'Retained Earnings' }],
	['currentYearResult', { code: '12', nameFr: 'Résultat de l\'exercice', nameEn: 'Current Year Result' }],
	['incomeSummary', { code: '129', nameFr: 'Résultat en instance d\'affectation', nameEn: 'Income Summary' }],
	['bankLoan', { code: '164', nameFr: 'Emprunts auprès des établissements de crédit', nameEn: 'Bank Loan' }],
	['leaseLiability', { code: '168', nameFr: 'Autres emprunts et dettes assimilées', nameEn: 'Lease Liability' }],
	['provisionForRisks', { code: '151', nameFr: 'Provisions pour risques', nameEn: 'Provision for Risks' }],
	['provisionForCharges', { code: '158', nameFr: 'Autres provisions pour charges', nameEn: 'Provision for Charges' }],
	['land', { code: '211', nameFr: 'Terrains', nameEn: 'Land' }],
	['buildings', { code: '213', nameFr: 'Constructions', nameEn: 'Buildings' }],
	['equipment', { code: '2154', nameFr: 'Matériel industriel', nameEn: 'Equipment' }],
	['furniture', { code: '2184', nameFr: 'Mobilier', nameEn: 'Furniture' }],
	['itEquipment', { code: '2183', nameFr: 'Matériel de bureau et informatique', nameEn: 'IT Equipment' }],
	['vehicles', { code: '2182', nameFr: 'Matériel de transport', nameEn: 'Vehicles' }],
	['accDeprBuildings', { code: '2813', nameFr: 'Amort. constructions', nameEn: 'Accum. Depr. Buildings' }],
	['accDeprEquipment', { code: '28154', nameFr: 'Amort. matériel industriel', nameEn: 'Accum. Depr. Equipment' }],
	['accDeprFurniture', { code: '28184', nameFr: 'Amort. mobilier', nameEn: 'Accum. Depr. Furniture' }],
	['accDeprVehicles', { code: '28182', nameFr: 'Amort. matériel transport', nameEn: 'Accum. Depr. Vehicles' }],
	['merchandise', { code: '37', nameFr: 'Stocks de marchandises', nameEn: 'Merchandise' }],
	['accountsPayable', { code: '401', nameFr: 'Fournisseurs', nameEn: 'Accounts Payable' }],
	['accountsReceivable', { code: '411', nameFr: 'Clients', nameEn: 'Accounts Receivable' }],
	['vatCollected', { code: '44571', nameFr: 'TVA collectée', nameEn: 'VAT Collected' }],
	['vatDeductible', { code: '44566', nameFr: 'TVA déductible sur biens et services', nameEn: 'VAT Deductible' }],
	['employeesPayable', { code: '421', nameFr: 'Personnel - rémunérations dues', nameEn: 'Employees Payable' }],
	['bank', { code: '512', nameFr: 'Banque', nameEn: 'Bank' }],
	['pettyCash', { code: '53', nameFr: 'Caisse', nameEn: 'Petty Cash' }],
	['purchasesMerchandise', { code: '607', nameFr: 'Achats de marchandises', nameEn: 'Purchases - Merchandise' }],
	['salaryExpense', { code: '641', nameFr: 'Rémunérations du personnel', nameEn: 'Salary Expense' }],
	['socialChargesExpense', { code: '645', nameFr: 'Charges de sécurité sociale', nameEn: 'Social Charges Expense' }],
	['depreciationExpense', { code: '681', nameFr: 'Dotations aux amortissements', nameEn: 'Depreciation Expense' }],
	['interestExpense', { code: '661', nameFr: 'Charges d\'intérêts', nameEn: 'Interest Expense' }],
	['exchangeLoss', { code: '666', nameFr: 'Pertes de change', nameEn: 'Exchange Loss' }],
	['incomeTaxExpense', { code: '695', nameFr: 'Impôt sur les bénéfices', nameEn: 'Income Tax Expense' }],
	['salesMerchandise', { code: '707', nameFr: 'Ventes de marchandises', nameEn: 'Sales - Merchandise' }],
	['serviceRevenue', { code: '706', nameFr: 'Prestations de services', nameEn: 'Service Revenue' }],
	['interestIncome', { code: '7624', nameFr: 'Revenus des prêts', nameEn: 'Interest Income' }],
	['exchangeGain', { code: '766', nameFr: 'Gains de change', nameEn: 'Exchange Gain' }],
	['disposalGain', { code: '775', nameFr: 'Produits des cessions d\'éléments d\'actif', nameEn: 'Gain on Disposal' }],
	['rentExpense', { code: '613', nameFr: 'Locations', nameEn: 'Rent Expense' }],
	['insuranceExpense', { code: '616', nameFr: 'Primes d\'assurance', nameEn: 'Insurance Expense' }],
	/* Extended PCG overrides */
	['statutoryReserve', { code: '1063', nameFr: 'Réserves statutaires', nameEn: 'Statutory Reserve' }],
	['constructionInProgress', { code: '231', nameFr: 'Immobilisations corporelles en cours', nameEn: 'Construction in Progress' }],
	['workInProgress', { code: '33', nameFr: 'En-cours de production', nameEn: 'Work in Progress' }],
	['accruedExpenses', { code: '4081', nameFr: 'Fournisseurs - factures non parvenues', nameEn: 'Accrued Expenses' }],
	['accruedRevenue', { code: '4181', nameFr: 'Clients - produits non encore facturés', nameEn: 'Accrued Revenue' }],
	['advancesToSuppliers', { code: '4091', nameFr: 'Fournisseurs - avances versées', nameEn: 'Advances to Suppliers' }],
	['incomeTaxPayable', { code: '444', nameFr: 'État - impôt sur les bénéfices', nameEn: 'Income Tax Payable' }],
	['otherReceivables', { code: '467', nameFr: 'Autres comptes débiteurs', nameEn: 'Other Receivables' }],
	['otherPayables', { code: '468', nameFr: 'Autres comptes créditeurs', nameEn: 'Other Payables' }],
	['dividendsPayable', { code: '457', nameFr: 'Associés - dividendes à payer', nameEn: 'Dividends Payable' }],
	['bankOverdraft', { code: '519', nameFr: 'Concours bancaires courants', nameEn: 'Bank Overdraft' }],
	['purchasesRawMaterials', { code: '601', nameFr: 'Achats de matières premières', nameEn: 'Purchases - Raw Materials' }],
	['costOfGoodsSold', { code: '6037', nameFr: 'Variation des stocks de marchandises', nameEn: 'COGS - Stock Variation' }],
	['inventoryVariation', { code: '6031', nameFr: 'Variation des stocks de matières premières', nameEn: 'Inventory Variation' }],
	['freightIn', { code: '6241', nameFr: 'Transports sur achats', nameEn: 'Freight In' }],
	['externalServices', { code: '62', nameFr: 'Autres services extérieurs', nameEn: 'External Services' }],
	['maintenanceExpense', { code: '615', nameFr: 'Entretien et réparations', nameEn: 'Maintenance Expense' }],
	['telecomExpense', { code: '626', nameFr: 'Frais postaux et de télécommunications', nameEn: 'Telecom Expense' }],
	['taxesAndDuties', { code: '63', nameFr: 'Impôts, taxes et versements assimilés', nameEn: 'Taxes & Duties' }],
	['provisionExpense', { code: '6815', nameFr: 'Dotations aux provisions pour risques', nameEn: 'Provision Expense' }],
	['exceptionalExpense', { code: '671', nameFr: 'Charges exceptionnelles sur opérations de gestion', nameEn: 'Exceptional Expense' }],
	['otherOperatingRevenue', { code: '75', nameFr: 'Autres produits de gestion courante', nameEn: 'Other Operating Revenue' }],
	['operatingSubsidies', { code: '74', nameFr: 'Subventions d\'exploitation', nameEn: 'Operating Subsidies' }],
	['inventoryProductionVar', { code: '7135', nameFr: 'Variation des stocks de produits finis', nameEn: 'Inventory Production Variation' }],
	['exceptionalIncome', { code: '771', nameFr: 'Produits exceptionnels sur opérations de gestion', nameEn: 'Exceptional Income' }],
	['reversalOfProvisions', { code: '7815', nameFr: 'Reprises sur provisions pour risques', nameEn: 'Reversal of Provisions' }],
	['salesFinishedGoods', { code: '701', nameFr: 'Ventes de produits finis', nameEn: 'Sales - Finished Goods' }],
	['prepaidExpenses', { code: '486', nameFr: 'Charges constatées d\'avance', nameEn: 'Prepaid Expenses' }],
	['unearnedRevenue', { code: '487', nameFr: 'Produits constatés d\'avance', nameEn: 'Unearned Revenue' }],
	['advancesFromCustomers', { code: '4191', nameFr: 'Clients - avances reçues', nameEn: 'Advances from Customers' }],
	['otherLtDebt', { code: '168', nameFr: 'Autres emprunts et dettes assimilées', nameEn: 'Other LT Debt' }],
	['inventoryProvision', { code: '39', nameFr: 'Dépréciations des stocks', nameEn: 'Inventory Provision' }],
	['finishedGoods', { code: '355', nameFr: 'Produits finis', nameEn: 'Finished Goods' }],
	['socialChargesPayable', { code: '43', nameFr: 'Sécurité sociale et autres organismes sociaux', nameEn: 'Social Charges Payable' }],
	['vatPayable', { code: '44551', nameFr: 'TVA à décaisser', nameEn: 'VAT Payable' }],
	['badDebtExpense', { code: '6817', nameFr: 'Dotations aux dépréciations des créances', nameEn: 'Bad Debt Expense' }],
	['rouAsset', { code: '212', nameFr: 'Droit au bail', nameEn: 'Right-of-Use Asset' }],
	['shortTermInvestments', { code: '50', nameFr: 'Valeurs mobilières de placement', nameEn: 'Short-Term Investments' }],
	['rawMaterials', { code: '31', nameFr: 'Matières premières', nameEn: 'Raw Materials' }],
	['allowanceDoubtful', { code: '491', nameFr: 'Dépréciations des comptes clients', nameEn: 'Allowance for Doubtful Accounts' }],
	['revaluationSurplus', { code: '1053', nameFr: 'Écarts de réévaluation', nameEn: 'Revaluation Surplus' }],
	['deferredTaxAsset', { code: '4486', nameFr: 'État - charges à répartir', nameEn: 'Deferred Tax Asset' }],
	['deferredTaxLiability', { code: '4486', nameFr: 'État - produits à répartir', nameEn: 'Deferred Tax Liability' }],
	['disposalLoss', { code: '675', nameFr: 'Valeur comptable des éléments cédés', nameEn: 'Loss on Disposal' }],
]);
