import type { FrameworkOverride } from '../types';

export const usgaapOverrides: Map<string, FrameworkOverride> = new Map([
	['shareCapital', { code: '-', nameFr: 'Common Stock', nameEn: 'Common Stock' }],
	['legalReserve', { code: '-', nameFr: 'Additional Paid-in Capital', nameEn: 'APIC' }],
	['retainedEarnings', { code: '-', nameFr: 'Retained Earnings', nameEn: 'Retained Earnings' }],
	['currentYearResult', { code: '-', nameFr: 'Net Income', nameEn: 'Net Income' }],
	['incomeSummary', { code: '-', nameFr: 'Income Summary', nameEn: 'Income Summary' }],
	['bankLoan', { code: '-', nameFr: 'Notes Payable', nameEn: 'Notes Payable' }],
	['leaseLiability', { code: '-', nameFr: 'Finance Lease Liability (ASC 842)', nameEn: 'Lease Liability' }],
	['provisionForRisks', { code: '-', nameFr: 'Contingent Liabilities', nameEn: 'Contingent Liabilities' }],
	['land', { code: '-', nameFr: 'Land', nameEn: 'Land' }],
	['buildings', { code: '-', nameFr: 'Buildings', nameEn: 'Buildings' }],
	['equipment', { code: '-', nameFr: 'Machinery & Equipment', nameEn: 'Equipment' }],
	['vehicles', { code: '-', nameFr: 'Vehicles', nameEn: 'Vehicles' }],
	['merchandise', { code: '-', nameFr: 'Inventory', nameEn: 'Inventory' }],
	['accountsPayable', { code: '-', nameFr: 'Accounts Payable', nameEn: 'Accounts Payable' }],
	['accountsReceivable', { code: '-', nameFr: 'Accounts Receivable', nameEn: 'Accounts Receivable' }],
	['bank', { code: '-', nameFr: 'Cash', nameEn: 'Cash' }],
	['pettyCash', { code: '-', nameFr: 'Petty Cash', nameEn: 'Petty Cash' }],
	['purchasesMerchandise', { code: '-', nameFr: 'Cost of Goods Sold', nameEn: 'COGS' }],
	['salaryExpense', { code: '-', nameFr: 'Salaries Expense', nameEn: 'Salaries Expense' }],
	['socialChargesExpense', { code: '-', nameFr: 'Payroll Tax Expense', nameEn: 'Payroll Tax Expense' }],
	['depreciationExpense', { code: '-', nameFr: 'Depreciation Expense', nameEn: 'Depreciation Expense' }],
	['interestExpense', { code: '-', nameFr: 'Interest Expense', nameEn: 'Interest Expense' }],
	['incomeTaxExpense', { code: '-', nameFr: 'Income Tax Expense', nameEn: 'Income Tax Expense' }],
	['salesMerchandise', { code: '-', nameFr: 'Sales Revenue', nameEn: 'Sales Revenue' }],
	['serviceRevenue', { code: '-', nameFr: 'Service Revenue', nameEn: 'Service Revenue' }],
	['interestIncome', { code: '-', nameFr: 'Interest Income', nameEn: 'Interest Income' }],
	['disposalGain', { code: '-', nameFr: 'Gain on Sale of Assets', nameEn: 'Gain on Disposal' }],
	['badDebtExpense', { code: '-', nameFr: 'Bad Debt Expense', nameEn: 'Bad Debt Expense' }],
	['rentExpense', { code: '-', nameFr: 'Rent Expense', nameEn: 'Rent Expense' }],
	['insuranceExpense', { code: '-', nameFr: 'Insurance Expense', nameEn: 'Insurance Expense' }],
	/* Extended US GAAP overrides */
	['statutoryReserve', { code: '-', nameFr: 'Additional Paid-in Capital', nameEn: 'Additional Paid-in Capital' }],
	['constructionInProgress', { code: '-', nameFr: 'Construction in Progress', nameEn: 'Construction in Progress' }],
	['workInProgress', { code: '-', nameFr: 'Work in Progress', nameEn: 'Work in Progress' }],
	['accruedExpenses', { code: '-', nameFr: 'Accrued Liabilities', nameEn: 'Accrued Liabilities' }],
	['accruedRevenue', { code: '-', nameFr: 'Unbilled Receivables', nameEn: 'Unbilled Receivables' }],
	['advancesToSuppliers', { code: '-', nameFr: 'Prepaid Purchases', nameEn: 'Prepaid Purchases' }],
	['socialChargesPayable', { code: '-', nameFr: 'Payroll Taxes Payable', nameEn: 'Payroll Taxes Payable' }],
	['incomeTaxPayable', { code: '-', nameFr: 'Income Tax Payable', nameEn: 'Income Tax Payable' }],
	['otherReceivables', { code: '-', nameFr: 'Other Receivables', nameEn: 'Other Receivables' }],
	['otherPayables', { code: '-', nameFr: 'Other Payables', nameEn: 'Other Payables' }],
	['dividendsPayable', { code: '-', nameFr: 'Dividends Payable', nameEn: 'Dividends Payable' }],
	['bankOverdraft', { code: '-', nameFr: 'Bank Overdraft', nameEn: 'Bank Overdraft' }],
	['purchasesRawMaterials', { code: '-', nameFr: 'Raw Materials Purchased', nameEn: 'Raw Materials Purchased' }],
	['costOfGoodsSold', { code: '-', nameFr: 'Cost of Goods Sold', nameEn: 'Cost of Goods Sold' }],
	['inventoryVariation', { code: '-', nameFr: 'Inventory Adjustment', nameEn: 'Inventory Adjustment' }],
	['freightIn', { code: '-', nameFr: 'Freight-In', nameEn: 'Freight-In' }],
	['externalServices', { code: '-', nameFr: 'Other Operating Expenses', nameEn: 'Other Operating Expenses' }],
	['maintenanceExpense', { code: '-', nameFr: 'Repairs & Maintenance', nameEn: 'Repairs & Maintenance' }],
	['telecomExpense', { code: '-', nameFr: 'Telephone & Internet', nameEn: 'Telephone & Internet' }],
	['taxesAndDuties', { code: '-', nameFr: 'Other Taxes', nameEn: 'Other Taxes' }],
	['provisionExpense', { code: '-', nameFr: 'Provision Expense', nameEn: 'Provision Expense' }],
	['exceptionalExpense', { code: '-', nameFr: 'Other Expenses', nameEn: 'Other Expenses' }],
	['otherOperatingRevenue', { code: '-', nameFr: 'Other Operating Revenue', nameEn: 'Other Operating Revenue' }],
	['operatingSubsidies', { code: '-', nameFr: 'Government Grants', nameEn: 'Government Grants' }],
	['inventoryProductionVar', { code: '-', nameFr: 'Change in Finished Goods Inventory', nameEn: 'Change in Finished Goods Inventory' }],
	['exceptionalIncome', { code: '-', nameFr: 'Other Income', nameEn: 'Other Income' }],
	['reversalOfProvisions', { code: '-', nameFr: 'Reversal of Provisions', nameEn: 'Reversal of Provisions' }],
	['salesFinishedGoods', { code: '-', nameFr: 'Sales Revenue - Finished Goods', nameEn: 'Sales Revenue - Finished Goods' }],
	['prepaidExpenses', { code: '-', nameFr: 'Prepaid Expenses', nameEn: 'Prepaid Expenses' }],
	['unearnedRevenue', { code: '-', nameFr: 'Unearned Revenue', nameEn: 'Unearned Revenue' }],
	['advancesFromCustomers', { code: '-', nameFr: 'Customer Deposits', nameEn: 'Customer Deposits' }],
	['otherLtDebt', { code: '-', nameFr: 'Other Long-Term Liabilities', nameEn: 'Other Long-Term Liabilities' }],
	['inventoryProvision', { code: '-', nameFr: 'Allowance for Inventory Obsolescence', nameEn: 'Allowance for Inventory Obsolescence' }],
	['finishedGoods', { code: '-', nameFr: 'Finished Goods', nameEn: 'Finished Goods' }],
	['rawMaterials', { code: '-', nameFr: 'Raw Materials', nameEn: 'Raw Materials' }],
	['rouAsset', { code: '-', nameFr: 'Right-of-Use Asset (ASC 842)', nameEn: 'Right-of-Use Asset' }],
	['vatCollected', { code: '-', nameFr: 'Sales Tax Payable', nameEn: 'Sales Tax Payable' }],
	['vatDeductible', { code: '-', nameFr: 'Sales Tax Receivable', nameEn: 'Sales Tax Receivable' }],
	['vatPayable', { code: '-', nameFr: 'Sales Tax Payable - Net', nameEn: 'Sales Tax Payable - Net' }],
	['provisionForCharges', { code: '-', nameFr: 'Estimated Liabilities', nameEn: 'Estimated Liabilities' }],
	['furniture', { code: '-', nameFr: 'Office Furniture & Fixtures', nameEn: 'Office Furniture & Fixtures' }],
	['itEquipment', { code: '-', nameFr: 'Computer Equipment', nameEn: 'Computer Equipment' }],
	['accDeprBuildings', { code: '-', nameFr: 'Accum. Depr. - Buildings', nameEn: 'Accum. Depr. Buildings' }],
	['accDeprEquipment', { code: '-', nameFr: 'Accum. Depr. - Equipment', nameEn: 'Accum. Depr. Equipment' }],
	['accDeprFurniture', { code: '-', nameFr: 'Accum. Depr. - Furniture', nameEn: 'Accum. Depr. Furniture' }],
	['accDeprVehicles', { code: '-', nameFr: 'Accum. Depr. - Vehicles', nameEn: 'Accum. Depr. Vehicles' }],
	['employeesPayable', { code: '-', nameFr: 'Salaries Payable', nameEn: 'Salaries Payable' }],
	['shortTermInvestments', { code: '-', nameFr: 'Short-Term Investments', nameEn: 'Short-Term Investments' }],
	['exchangeLoss', { code: '-', nameFr: 'Foreign Exchange Loss', nameEn: 'Foreign Exchange Loss' }],
	['exchangeGain', { code: '-', nameFr: 'Foreign Exchange Gain', nameEn: 'Foreign Exchange Gain' }],
	['allowanceDoubtful', { code: '-', nameFr: 'Allowance for Doubtful Accounts', nameEn: 'Allowance for Doubtful Accounts' }],
	['revaluationSurplus', { code: '-', nameFr: 'Revaluation Surplus', nameEn: 'Revaluation Surplus' }],
	['deferredTaxAsset', { code: '-', nameFr: 'Deferred Tax Asset', nameEn: 'Deferred Tax Asset' }],
	['deferredTaxLiability', { code: '-', nameFr: 'Deferred Tax Liability', nameEn: 'Deferred Tax Liability' }],
	['disposalLoss', { code: '-', nameFr: 'Loss on Disposal of Assets', nameEn: 'Loss on Disposal' }],
]);
